# WHAT IS PYTORCH?

It’s a Python-based scientific computing package targeted at two sets of audiences:

- A replacement for NumPy to use the power of GPUs
- a deep learning research platform that provides maximum flexibility and speed

https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py

In [2]:
from __future__ import print_function
import torch

# Tensors

- Tensors are similar to NumPy’s ndarrays, 
- Tensors can also be used on a GPU to accelerate computing.

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00, -3.6893e+19,  2.5462e-30],
        [ 4.6577e-10,  3.8381e-21,  1.4013e-45],
        [ 1.4445e-31,  1.4013e-45,  9.4660e-30],
        [ 1.4013e-45,  5.2984e-31,  1.4013e-45],
        [ 1.4380e-31,  1.4013e-45,  1.4456e-31]])


In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.2894, 0.2598, 0.6488],
        [0.3679, 0.6812, 0.2128],
        [0.6519, 0.7041, 0.1428],
        [0.2544, 0.0921, 0.9702],
        [0.9431, 0.2233, 0.8811]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [8]:
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      

tensor([[ 1.3408, -0.9110, -0.9009],
        [ 1.4957, -0.2779,  1.2966],
        [ 0.9188, -0.4975,  0.1192],
        [-0.4981, -0.9400, -1.5103],
        [-0.9557, -0.4145,  0.5145]])


In [9]:
print(x.size())

torch.Size([5, 3])


# Operations


In [10]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.9638, -0.2579, -0.5608],
        [ 2.3113,  0.1591,  1.6878],
        [ 1.3907, -0.2994,  0.1501],
        [-0.1211, -0.1535, -0.5948],
        [ 0.0149,  0.5043,  1.3007]])


In [11]:
print(torch.add(x, y))

tensor([[ 1.9638, -0.2579, -0.5608],
        [ 2.3113,  0.1591,  1.6878],
        [ 1.3907, -0.2994,  0.1501],
        [-0.1211, -0.1535, -0.5948],
        [ 0.0149,  0.5043,  1.3007]])


In [12]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.9638, -0.2579, -0.5608],
        [ 2.3113,  0.1591,  1.6878],
        [ 1.3907, -0.2994,  0.1501],
        [-0.1211, -0.1535, -0.5948],
        [ 0.0149,  0.5043,  1.3007]])


In [13]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.9638, -0.2579, -0.5608],
        [ 2.3113,  0.1591,  1.6878],
        [ 1.3907, -0.2994,  0.1501],
        [-0.1211, -0.1535, -0.5948],
        [ 0.0149,  0.5043,  1.3007]])
